add error checking, move usage from .help files to usage() in each script

diff --git a/Scripts/addMergeCalendar b/Scripts/addMergeCalendar
--- a/Scripts/addMergeCalendar
+++ b/Scripts/addMergeCalendar
@@ -1,5 +1,23 @@
 #!/bin/bash
 
+usage() {
+    echo ""
+    echo "Usage: `basename $0` param1"
+    echo ""
+    echo "  Description:"
+    echo "    Adds a new merge calendar to the .mergeCalendars file."
+    echo ""
+    echo "  Parameters:"
+    echo "    - param1 : Merge Calendar Name"
+    exit 1
+}
+
+if [[ ( $@ == "--help") ||  $@ == "-h" ]] 
+then 
+  usage
+  exit 0
+fi 
+
 if ! [ -f .mergeCalendars ] || [ `cat .mergeCalendars | wc -l` -eq 0 ]
 then
   touch .mergeCalendars
@@ -7,7 +25,7 @@ fi
 
 if [ -z "$1" ]
 then 
-  cat $0.help
+  echo "ERROR: Merge Calendar Name is required."
   exit 1
 fi
 
@@ -15,4 +33,5 @@ newCalendarKey=`openssl rand -base64 20 | md5`
 
 echo "$1|$newCalendarKey|" >> .mergeCalendars
 
-echo "Your new merged calendar has been added to the bottom of the .mergeCalendars file, please open the file and update the list of source calendars to merge"
+echo "SUCCESS: Your new merged calendar ""$1"" with a key of ""$newCalendarKey"" has been added to the bottom of the .mergeCalendars file."
+echo "         Please open the file and update the list of source calendars to start merging to this calendar."
diff --git a/Scripts/addSourceCalendar b/Scripts/addSourceCalendar
--- a/Scripts/addSourceCalendar
+++ b/Scripts/addSourceCalendar
@@ -1,5 +1,24 @@
 #!/bin/bash
 
+usage() {
+    echo ""
+    echo "Usage: `basename $0` param1 param2"
+    echo ""
+    echo "  Description:"
+    echo "    Adds a new source calendar to the .sourceCalendars file."
+    echo ""
+    echo "  Parameters:"
+    echo "    - param1 : Calendar Name"
+    echo "    - param2 : Calendar URL (must be valid)"
+    exit 1
+}
+
+if [[ ( $@ == "--help") ||  $@ == "-h" ]] 
+then 
+  usage
+  exit 0
+fi 
+
 if ! [ -f .sourceCalendars ] || [ `cat .sourceCalendars | wc -l` -eq 0 ]
 then
   touch .sourceCalendars
@@ -7,16 +26,27 @@ fi
 
 if [ -z "$1" ]
 then
-  echo "Please send the name of the new source calendar when calling this script in the first position."
-  cat $0.help
+  echo "ERROR: Calendar Name is required."
+  usage
   exit 1
 fi
 
 if [ -z "$2" ]
 then
-  echo "Please send the url of the new source calendar when calling this script in the second position."
-  cat $0.help
+  echo "ERROR: Calendar URL is required."
+  usage
   exit 1
 fi
 
-echo "$1|$2" >> .sourceCalendars
+calendarIsValid=$(wget --server-response -O /dev/null "$2" 2>&1 | grep -c 'HTTP/1.1 200 OK')
+
+if [ "$calendarIsValid" == 1 ]
+then 
+  echo "$1|$2" >> .sourceCalendars
+else
+  echo "ERROR: Calendar URL is invalid."
+  usage
+  exit 2
+fi
+
+echo "SUCCESS: Your new source calendar ""$1"" with a url of ""$2"" has been added to the bottom of the .sourceCalendars file."
diff --git a/Scripts/downloadSourceCalendars b/Scripts/downloadSourceCalendars
--- a/Scripts/downloadSourceCalendars
+++ b/Scripts/downloadSourceCalendars
@@ -1,14 +1,37 @@
 #!/bin/bash
 
+usage() {
+    echo ""
+    echo "Usage: `basename $0` param1 param2"
+    echo ""
+    echo "  Description:"
+    echo "    Downloads all source calendars listed in .sourceCalendars, extracts all events,"
+    echo "    prepend the description field with the source calendar name and save the data in"
+    echo "    the SourceCalendars directory."
+    echo ""
+    echo "  Dependancy:"
+    echo "    The file .sourceCalendars is required and can be populated by calling the script"
+    echo "    Script/addSourceCalendar"
+    exit 1
+}
+
+if [[ ( $@ == "--help") ||  $@ == "-h" ]] 
+then 
+  usage
+  exit 0
+fi 
+
 if ! [ -f .sourceCalendars ] || [ `cat .sourceCalendars | wc -l` -eq 0 ]
 then
-  cat $0.help
+  usage
   exit 1
 fi
 
 while read sourceCalendar; do
   calendarName=$(echo $sourceCalendar | cut -f1 -d\|)
+  calendarFilename=$(echo $sourceCalendar | cut -f1 -d\|)
+  calendarFilename=${calendarFilename//\ /}.ics
   calendarURL=$(echo $sourceCalendar | cut -f2 -d\|)
-  echo "Downloading source calendar \"$calendarName\" and extracting events to ./SourceCalendars/\"$calendarName.ics\""
-  wget -q -O - "$calendarURL" | sed -n '/BEGIN:VEVENT/,/END:VEVENT/p' | sed -e 's/SUMMARY:/SUMMARY:'$calendarName': /g' > ./SourceCalendars/"$calendarName.ics"
+  echo "Downloading source calendar \"$calendarName\" and extracting events to ./SourceCalendars/\"$calendarFilename\""
+  wget -q -O - "$calendarURL" | sed -n '/BEGIN:VEVENT/,/END:VEVENT/p' | sed -e 's/DESCRIPTION:/DESCRIPTION:(From calendar "'"$calendarName"'")\ /g' > ./SourceCalendars/"$calendarFilename"
 done <.sourceCalendars
